apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-basic-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: website-basic-frontend
  template:
    metadata:
      labels:
        component: website-basic-frontend
    spec:
      containers:
        - name: website-basic
          image: DOCKERHUB_USERNAME/website-basic-image
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
