apiVersion: v1
kind: Service
metadata:
  name: website-basic-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: website-basic-frontend
  ports:
    - port: 3000
      targetPort: 3000
