name: Push images

on:
  workflow_call:
    inputs:
      DOCKER_IMAGE_NAME:
        required: true
        type: string
      REPO_SHA:
        required: true
        type: string
      DOCKER_IMAGE_CONTEXT:
        required: true
        type: string
      DOCKER_FILE_PATH:
        required: true
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  push-images-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login To Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Push Frontend Image
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.DOCKER_IMAGE_CONTEXT}}
          file: ${{ inputs.DOCKER_FILE_PATH}}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.DOCKER_IMAGE_NAME }}:latest,${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.DOCKER_IMAGE_NAME }}:${{ inputs.REPO_SHA }}
